name: cron

on: [push]

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Run npm steps
      run: |
        cd ..
        git clone https://github.com/abap-openapi/abap-openapi-client.git
        cd abap-openapi-client
        npm install && npm test
        rm ./test/generated/*.abap
        node index.js https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json githubcom
        node index.js https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-2.18/ghes-2.18.json ghes218
        node index.js https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-2.19/ghes-2.19.json ghes219
        node index.js https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-2.20/ghes-2.20.json ghes220
        node index.js https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-2.21/ghes-2.21.json ghes221
        node index.js https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-2.22/ghes-2.22.json ghes222
        node index.js https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-3.0/ghes-3.0.json ghes30
        node index.js https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/github.ae/github.ae.json githubae
        ls
        cp ./test/generated/*.abap ../generated-github/
        cd ../generated-github/
        ls
        git status