name: cron

on: [push]

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Run npm steps
      run: |
        cd ..
        git clone https://github.com/abap-openapi/abap-openapi-client.git
        ls