name: cron

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Run npm steps
      run: |
        cd ..
        git clone https://github.com/abap-openapi/abap-openapi-client.git
        cd abap-openapi-client
        npm install && npm test
        rm ./test/generated/*.abap
        node index.js https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json githubcom
        ls
        cp ./test/generated/*.abap ../generated-github/
        cd ../generated-github/
        ls
        git status
    - name: Push
      if: github.ref == 'refs/heads/main'
      run: |
        git status
        git config --global user.email "actions@github.com"
        git config --global user.name "Actions CI"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Automatic update"
        git push
